import type { Metadata } from 'next';
import { Noto_Sans, Gruppo, Noto_Sans_Display } from 'next/font/google';
import './globals.scss';

const noto = Noto_Sans({ subsets: ['latin'] });
const gruppo = Gruppo({ weight: '400', subsets: ['latin'], variable: '--font-display' });

export const metadata: Metadata = {
  title: 'Ash Johns - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.className} ${gruppo.variable}`}>
        <div className="stars-sm" />
        <div className="stars-lg" />
        {children}
      </body>
    </html>
  );
}
